if GetLocale() == "ruRU" then
DBM_SW_TAB						= "SunwellTab"
DBM_SUNWELL						= "Солнечный Колодец"

-- Kalecgos
DBM_KAL_NAME					= "Калесгос"
DBM_KAL_DESCRIPTION 			= "Объявляет и показывает таймеры для Дыхание льда, Дикая магия и Проклятие безграничной агонии."

DBM_KAL_KILL_NAME				= "Сатроварр Осквернитель"
DBM_KAL_DEMON_SHORT				= "Сатроварр"

DBM_KAL_OPTION_BREATH			= "Объявить Дыхание льда"
DBM_KAL_OPTION_PREBREATH		= "Показать предупреждение \"Скоро Дыхание льда\""
DBM_KAL_OPTION_WM_WARN			= "Объявить Дикая магия"
DBM_KAL_OPTION_WM_WHISPER		= "Сообщить цели Дикая магия"
DBM_KAL_OPTION_COA_WARN			= "Объявить Проклятие безграничной агонии"
DBM_KAL_OPTION_COA_ICON			= "Установить метку на цель Проклятие безграничной агонии"
DBM_KAL_OPTION_PORT_PREWARN		= "Показать предупреждение \"Скоро Портал\""
DBM_KAL_OPTION_PORT_WARN		= "Объявить Порталы"
DBM_KAL_OPTION_WM_WARN2			= "Показать отрицательный эффект Дикая магия"
DBM_KAL_OPTION_SHOWFRAME		= "Показать границы Призрачного мира"
DBM_KAL_FRAME_UPWARDS			= "Развернуть вверх границы Призрачного мира"
DBM_KAL_FRAME_UPWARDS2			= "Развернуть вверх"
DBM_KAL_FRAME_COLORS			= "Использовать цвета классов"
DBM_KAL_OPTION_RANGE			= "Показать область границы контроля"
DBM_KAL_OPTION_STRIKE			= "Объявить Сокрушающий удар"
DBM_KAL_OPTION_FRAME			= "Показать фрейм здоровья"

DBM_KAL_SPELLID_BREATH			= 44799
DBM_KAL_SPELLIDS_WM				= { -- DO NOT TRANSLATE (should be moved to kalecgos.lua!)
	[44978] = "Heal",	-- Healing done by spells and effects increased by 100%.
	[45001] = "Cast",	-- Casting time increased by 100%.
	[45002] = "Hit",	-- Chance to hit with melee and ranged attacks reduced by 50%.
	[45004] = "Crit",	-- Damage done by critical hits increased by 100%.
	[45006] = "Aggro",	-- Increases threat generated by 100%.
	[45010] = "Cost"	-- Spell and ability costs reduced by 50%.
}
DBM_KAL_SPELLID_COA1			= 45032
DBM_KAL_SPELLID_COA2			= 45034
DBM_KAL_SPELLID_PORT1			= 46021
DBM_KAL_SPELLID_BLAST			= 44866
DBM_KAL_SPELLID_BUFFET			= 45018
DBM_KAL_YELL_PULL				= "Аххх! Я больше никогда не буду рабом Малигоса! Осмелься бросить мне вызов – и я уничтожу тебя"

DBM_KAL_WARN_BREATH				= "Дыхание льда"
DBM_KAL_WARN_BREATH_SOON		= "Скоро Дыхание льда"
DBM_KAL_WHISPER_WM				= "Дикая магия: %s"
DBM_KAL_WARN_COA				= "Проклятие безграничной агонии: >%s<"
DBM_KAL_WARN_PORT				= "Портал #%d: >%s< (Группа %d)"
DBM_KAL_WARN_PORT_SOON			= "Скоро Портал #%d"
DBM_KAL_WARN_STRIKE				= "Сокрушающий удар по >%s<"

DBM_KAL_WARN_CASTTIME			= "+100% к времени наложения заклинаний"
DBM_KAL_WARN_HIT				= "-50% вероятности нанесения удара"
DBM_KAL_WARN_CRIT				= "+100% к шансу нанести критический удар"
DBM_KAL_WARN_AGGRO				= "+100% к вырабатыванию угрозы"
DBM_KAL_WARN_COST				= "-50% урона от заклинаний"
DBM_KAL_WARN_HEAL				= "+100% к лечению"

DBM_KAL_FRAME_TITLE				= "Призрачный мир"
DBM_KAL_MENU_LOCK				= "Закрепить границы"
DBM_KAL_FRAME_HIDE				= "Скрыть границы"

DBM_KAL_HEALTHFRAME_TITLE		= "Здоровье дракона/демона"

DBM_SBT["Arcane Buffet"]		= "Борьба Чар";
DBM_SBT["Frost Breath"]			= "Дыхание льда";
DBM_SBT["Next Portal"]			= "Следующий Портал";
DBM_SBT["Portal"]				= "Портал";
DBM_SBT["Ported"]				= "Предвестье";
DBM_SBT["Exhausted"]			= "Изнемогший";
DBM_SBT["Kal"] = {
	[1] = {"CoA: (.*)", "Проклятие: %1"},
	[2] = {"Next Portal #(.*)", "Следующий Портал #%1"},
	[3] = {"Portal #(.*)", "Портал #%1"},	
}
DBM_SBT["Калесгос"] = DBM_SBT["Kal"]

-- Brutallus 
DBM_BRUTALLUS_NAME				= "Бруталл" 
DBM_BRUTALLUS_DESCRIPTION		= "Объявляет и показывает таймеры для Палящее пламя и Ярость." 

DBM_BRUTALLUS_YELL_PULL			= "О, а вот и новые агнцы идут на заклание!"

DBM_BRUTALLUS_OPTION_BURN		= "Объявить Палящее пламя"
DBM_BRUTALLUS_OPTION_BURN2		= "Объявить отрицательный эффект Палящее пламя"
DBM_BRUTALLUS_OPTION_BAR_BURN2	= "Палящее пламя получил: <target>"
DBM_BRUTALLUS_OPTION_METEOR		= "Объявить Метеор"
DBM_BRUTALLUS_OPTION_STOMP		= "Объявить Топот"
DBM_BRUTALLUS_OPTION_BURN3		= "Установить метку на цель Палящее пламя"
DBM_BRUTALLUS_OPTION_BURN4		= "Показать спец-предупреждение, когда вы получили Палящее пламя"
DBM_BRUTALLUS_OPTION_DEL_BURN	= "Показать таймер Палящего пламени"
DBM_BRUTALLUS_OPTION_DEL_BURN2	= "Показать уведомление Палящее пламя"
DBM_BRUTALLUS_OPTION_PRESTOMP	= "Показать 5 секундное предупреждение перед Топот"

DBM_BRUTALLUS_WARN_BURN			= "Палящее пламя: >%s<"
DBM_BRUTALLUS_WHISP_BURN		= "Палящее пламя на вас!"
DBM_BRUTALLUS_WARN_STOMP		= "Топот: >%s<"
DBM_BRUTALLUS_WARN_METEOR		= "Метеор"
DBM_BRUTALLUS_WARN_DEL_BURN		= "Палящее пламя 15 секунд на >%s<"
DBM_BRUTALLUS_WARN_STOMP_SOON	= "Топот через 5 секунд"

DBM_SBT["Enrage"]		        = "Ярость";
DBM_SBT["Next Burn"]	        = "Следуещее Палящее пламя";
DBM_SBT["Next Meteor"]	        = "Следующий Метеор";
DBM_SBT["Next Stomp"]	        = "Следующий Топот";
DBM_SBT["Brutallus"] = {
	[1] = {"Burn: (.*)", "Палящее пламя: %1"},
	[2] = {"Jumped Burn: (.*)", "Палящее пламя: %1"},
}
DBM_SBT["Бруталл"] = DBM_SBT["Brutallus"]

-- Felmyst
DBM_FELMYST_NAME				= "Пророк Скверны"
DBM_FELMYST_DESCRIPTION			= "Объявляет Газ Огненной звезды, Глубокое Дыхание и Демонические испарения."

DBM_FELMYST_OPTION_SPECGAS		= "Показать спец-предупреждение Газ Огненной звезды"
DBM_FELMYST_OPTION_GASSOON		= "Показать предупреждение \"Скоро Газ Огненной звезды\""
DBM_FELMYST_OPTION_BREATH_SOON	= "Показать предупреждение \"Скоро Глубокое Дыхание\""
DBM_FELMYST_OPTION_VAPOR		= "Объявить цель Демонические испарения"

DBM_FELMYST_EMOTE_BREATH		= "%s выдыхает глубоким дыханием."

DBM_FELMYST_WARN_GAS			= "Газ Огненной звезды"
DBM_FELMYST_WARN_GAS_SOON		= "Скоро Газ Огненной звезды"
DBM_FELMYST_WARN_ENCAPS			= "Инкапсуляция: >%s<"
DBM_FELMYST_WARN_AIR			= "Воздушная Фаза"
DBM_FELMYST_LAND_SOON			= "Наземная фаза через 10 секунд"
DBM_FELMYST_BREATH_SOON_FMT		= "Глубокое Дыхание #%d через 10 секунд"
DBM_FELMYST_BREATH_SOON5_FMT	= "Глубокое Дыхание #%d через 5 секунд"
DBM_FELMYST_BREATH_NOW_FMT		= "Глубокое Дыхание #%d"
DBM_FELMYST_ENCAPS_WARN_SAY		= "Инкапсуляция на мне! Бегите!"
DBM_FELMYST_WARN_VAPOR			= "Демонические испарения: >%s<"

DBM_SBT["Enrage"]			    = "Ярость";
DBM_SBT["Air Phase"]		    = "Воздушная Фаза";
DBM_SBT["Ground Phase"]		    = "Наземная фаза";
DBM_SBT["Next Gas Nova"]	    = "Следующий Газ Огненной звезды";
DBM_SBT["Gas Nova"]			    = "Газ Огненной звезды";
DBM_SBT["Next Deep Breath"]	    = "Следуешее Глубокое Дыхание";
DBM_SBT["Deep Breath"]		    = "Глубокое Дыхание";

-- Eredar Twins
DBM_TWINS_NAME					= "Эредарские близнецы"
DBM_TWINS_DESCRIPTION			= "Объявляет и показывает таймеры для Теневые клинки, Кольцо Тьмы, Пирогенез и Воспламенение."
DBM_TWINS_OPTION_BLADES			= "Объявить Теневые клинки"
DBM_TWINS_OPTION_BUFF			= "Объявить Пирогенез"
DBM_TWINS_OPTION_BLOW			= "Объявить Сбить с толку"
DBM_TWINS_OPTION_BLOW_SOON		= "Показать предупреждение \"Скоро Сбить с толку\""
DBM_TWINS_OPTION_CONFLAG		= "Воспламенение: уведомление"
DBM_TWINS_OPTION_CONFLAG2		= "Воспламенение: сообщение шепотом"
DBM_TWINS_OPTION_CONFLAG3		= "Воспламенение: спец-предупреждение"
DBM_TWINS_OPTION_CONFLAG4		= "Воспламенение: метка"
DBM_TWINS_OPTION_CONFLAG5		= "Воспламенение: звуковое уведомление"
DBM_TWINS_OPTION_NOVA			= "Кольцо Тьмы: уведомление"
DBM_TWINS_OPTION_NOVA2			= "Кольцо Тьмы: сообщение шепотом"
DBM_TWINS_OPTION_NOVA3			= "Кольцо Тьмы: спец-предупреждение"
DBM_TWINS_OPTION_NOVA4			= "Кольцо Тьмы: метка"
DBM_TWINS_OPTION_TOUCH1			= "Показать спец-предупреждение, когда отрицательный эффект Затронутый тьмой"
DBM_TWINS_OPTION_TOUCH2			= "Показать спец-предупреждение, когда отрицательный эффект Тот, кого коснулось пламя"

DBM_TWINS_MOB_WL				= "Главная чернокнижница Алитесса"
DBM_TWINS_MOB_SOCR				= "Леди Сакролаш"
DBM_TWINS_EMOTE_CONFLAG			= "Алитесса наносит (.+) урона заклинанием Воспламенение"
DBM_TWINS_EMOTE_NOVA			= "Сакролаш наносит (.+)% урона заклинанием Кольцо Тьмы."

DBM_TWINS_WARN_BLADES			= "Теневые клинки"
DBM_TWINS_WARN_NOVA_ON			= "Кольцо Тьмы: >%s<"
DBM_TWINS_WARN_BUFF				= "Пирогенез"
DBM_TWINS_WARN_CONFLAG_ON		= "Воспламенение: >%s<"
DBM_TWINS_WARN_BLOW_SOON		= "Скоро Сбить с толку"
DBM_TWINS_WARN_BLOW				= "Сбить с толку"
DBM_TWINS_WHISPER_CONFLAG		= "Воспламенение на вас!"
DBM_TWINS_WHISPER_NOVA			= "Кольцо Тьмы на вас!"

DBM_TWINS_SPECWARN_SHADOW		= "Затронутый тьмой: %d"
DBM_TWINS_SPECWARN_FIRE			= "Тот, кого коснулось пламя: %d"

DBM_SBT["Shadow Blades"]		= "Теневые клинки";
DBM_SBT["Next Shadow Blades"]	= "Следующие Теневые клинки";
DBM_SBT["Next Shadow Nova"]		= "Следующее Кольцо Тьмы";
DBM_SBT["Shadow Nova"]			= "Кольцо Тьмы";
DBM_SBT["Confounding Blow"]		= "Сбить с толку";
DBM_SBT["Next Confounding Blow"]	= "Следующее Сбить с толку";

-- M'uru
DBM_MURU_NAME					= "М'ару"
DBM_MURU_DESCRIPTION			= "Объявляет Исчадие тьмы, Черные дыры, Часовых Бездны и возрождение гуманоидов."
DBM_MURU_OPTION_VOID			= "Объявить Часовые Бездны"
DBM_MURU_OPTION_VOID_SOON		= "Показать 5 секундное предупреждение перед Часовыми Бездны"
DBM_MURU_OPTION_HUM				= "Объявить Гуманоиды"
DBM_MURU_OPTION_HUM_SOON		= "Показать 5 секундное предупреждение перед возрождением гуманоидов"
DBM_MURU_OPTION_DARKNESS		= "Объявить Исчадие тьмы в фазе 1"
DBM_MURU_OPTION_DARKNESS_SOON	= "Показать предупреждение \"Скоро Исчадие тьмы\""
DBM_MURU_OPTION_HOLE_WARN		= "Объявить Черная дыра"
DBM_MURU_OPTION_HOLE_SOON_WARN	= "Показать предупреждение \"Скоро Черная дыра\""
DBM_MURU_OPTION_WARN_FIEND		= "Объявить Исчадие тьмы в фазе 2"

DBM_MURU_ENTROPIUS				= "Энтропий"

DBM_MURU_DARKNESS_SOON			= "Исчадие тьмы через 5 секунд"
DBM_MURU_DARKNESS_INC			= "Исчадие тьмы"
DBM_MURU_WARN_VOID_SOON			= "Часовой Бездны через 5 секунд"
DBM_MURU_WARN_VOID_NOW			= "Возрождение Часового Бездны"
DBM_MURU_WARN_HUMANOIDS_SOON	= "Гуманоиды через 5 секунд"
DBM_MURU_WARN_HUMANOIDS_NOW		= "Возрождение гуманоидов"
DBM_MURU_WARN_FIEND				= "Возрождение Исчадия тьмы"
DBM_MURU_WARN_BLACKHOLE			= "Порождение Черной дыры"
DBM_MURU_WARN_BLACKHOLE_SOON	= "Скоро Черная дыра"
DBM_MURU_WARN_P2				= "Фаза 2"

DBM_SBT["Enrage"]				= "Ярость";
DBM_SBT["Humanoids"]			= "Гуманоиды";
DBM_SBT["Void Sentinel"]		= "Часовой Бездны";
DBM_SBT["Next Darkness"]		= "Следующие Исчадия тьмы";
DBM_SBT["Next Black Hole"]		= "Следующая Черная дыра";

-- Kil'jaeden
DBM_KIL_NAME					= "Кил'джеден"
DBM_KIL_DESCRIPTION				= "Объявляет Сферы, Тьма, Щит, Отражения и Огненный цвет"

DBM_KIL_OPTION_RANGE			= "Показать область границы контроля"
DBM_KIL_OPTION_SHIELD			= "Объявить Щит Синевы"
DBM_KIL_OPTION_ORB				= "Объявить Сферы"
DBM_KIL_OPTION_FIRETARGET		= "Объявить Огненный цвет"
DBM_KIL_OPTION_FIRESAY			= "Отправить сообщение в чат, если бросается Огненный цвет"
DBM_KIL_OPTION_FIREWHISP		= "Сообщить шепотом цели о Огненный цвет"
DBM_KIL_OPTION_FIREICON			= "Установить метку на цель Огненный цвет"
DBM_KIL_OPTION_SHOWFRAME		= "Показать перечень целей Огненный цвет"
DBM_KIL_OPTION_WARNREFL			= "Объявить Зеркальные изображения"
DBM_KIL_OPTION_DARTS			= "Объявить Пламенный дротик"
DBM_KIL_OPTION_DRAGONORB		= "Объявить Сферы дракона"

DBM_KIL_YELL_PULL				= "Жалкие твари уничтожены. Да будет так! Я сделаю то, что не удалось Саргерасу. Я выпущу кровь из этого мерзкого мира и стану истинным повелителем Пылающего Легиона! Конец близок! Да свершится падение этого мира"
DBM_KIL_YELL_PHASE2_1			= "Враг среди вас!" -- this actually announces Sinister Reflections and not phase 2
DBM_KIL_YELL_PHASE2_2			= "Кому ты можешь верить!"

DBM_KIL_WARN_PHASE1				= "Фаза 2"
DBM_KIL_WARN_PHASE2				= "Фаза 3"
DBM_KIL_WARN_PHASE3				= "Фаза 4 - Метеориты"
DBM_KIL_WARN_PHASE4				= "Фаза 5 - Ярость"
DBM_KIL_WARN_SHIELD				= "Щит Синевы"
DBM_KIL_WARN_DARKNESS			= "Тьма"
DBM_KIL_WARN_DARKNESS_SOON		= "Скоро Тьма"
DBM_KIL_WARN_ORB				= "Возрождение Сферы"
DBM_KIL_WARN_ORBS				= "Возрождение Сфер"
--DBM_KIL_WARN_FIRE				= "Fire Bloom incoming"
DBM_KIL_WARN_FIRE_ON			= "Огненный цвет: >%s<"
DBM_KIL_WARN_DARKNESS_NOW		= "Тьма Тысячи Душ"
DBM_KIL_WARN_REFLECTIONS		= "Зеркальные изображения"
DBM_KIL_WARN_FIRE_SAY			= "Огненный цвет на мне!"
DBM_KIL_WARN_FIRE_WHISPER		= "Огненный цвет на вас!"
DBM_KIL_WARN_DARTS_SOON			= "Пламенный дротик через 5 секунд"
DBM_KIL_WARN_DARTS				= "Пламенный дротик"
DBM_KIL_WARN_DRAGORB_SOON		= "Сфера дракона через 5 секунд"
DBM_KIL_WARN_DRAGORB_NOW		= "Возрождение Сферы дракона"

DBM_KIL_FRAME_TITLE				= "Огненный цвет"

DBM_KIL_MENU_LOCK				= DBM_KAL_MENU_LOCK
DBM_KIL_FRAME_COLORS			= DBM_KAL_FRAME_COLORS
DBM_KIL_FRAME_UPWARDS			= "Развернуть перечень целей Огненного цвета вверх"
DBM_KIL_FRAME_UPWARDS2			= DBM_KAL_FRAME_UPWARDS2
DBM_KIL_FRAME_HIDE				= DBM_KAL_FRAME_HIDE

DBM_SBT["Fire Bloom CD"]		= "Огненный цвет";
DBM_SBT["Flame Darts"]			= "Пламенный дротик";
DBM_SBT["Dragon Orb"]			= "Сфера дракона";

end
